title: "拾遗集"
author: "漼时宜"
description: "不属于任何人，也不拥有任何人。"
remote_theme: jekyll/minima@v2.5.1

# 插件声明
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

# 核心样式：暗黑模式
minima:
  skin: dark

# 语法高亮
markdown: kramdown
highlighter: rouge
