baseURL = 'https://miss-shiyi.github.io/miss-shiyi/'
languageCode = 'zh-cn'
title = '拾遗集'
theme = 'hugo-theme-stack'

[params]
    mainSections = ["posts"]
    featuredImageField = "image"
    # 侧边栏配置
    sidebar = { avatar = "https://github.com/miss-shiyi.png", title = "漼时宜", subtitle = "不属于任何人，也不拥有任何人。" }

[markup.goldmark.renderer]
    unsafe = true # 必须开启，否则无法解析某些 Issue 里的 HTML

[markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github-dark"
