name: Sync Articles

on:
  issues:
    types: [opened, edited, labeled, unlabeled, reopened, closed, deleted]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run
        env:
          G_T: ${{ secrets.G_T }}
        run: |
          pip install requests
          python sync.py

      - name: Commit Main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md BACKUP/
          git commit -m "chore: update backup and readme" || exit 0
          git push

      - name: Push Wiki
        env:
          G_T: ${{ secrets.G_T }}
        run: |
          git clone "https://x-access-token:${G_T}@github.com/${{ github.repository }}.wiki.git" wiki_repo
          cd wiki_repo
          rm -rf ./*.md
          cp -r ../wiki_temp/*.md .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "docs: sync wiki"
            BRANCH=$(git remote show origin | grep 'HEAD branch' | cut -d' ' -f5)
            git push origin $BRANCH
          fi
